### ISSUE TITLE
Uploading CSV does not update item selection

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu-dev/ReportGenerator#112]
I am trying to use ReportGenerator for doing a Prevalence report. I attach my PeriodPrevalence results named "PeriodPrev_All.csv"  and I don't get any options for columns:

![image](https://github.com/darwin-eu-dev/ReportGenerator/assets/44193724/0fa929cc-0175-4d1e-962c-1563ccd75a1d)

Do I need to click something else for it to work?

**Comment by cbarbozaerasmus** [comment]
Hi, sorry for the delay of my answer. I fixed this problem and was related mainly to updates on IncidencePrevalence. Next week I am doing a new release, and I am creating a vignette to explain what type and how to load data in ReportGenerator. We hope that OMOP Generics will solve in some way this kind of issues of compatibility.
