### ISSUE TITLE
Uploading CSV does not update item selection - treatment patterns

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/ReportGenerator#113]
Hi @cbarbozaerasmus , I tried uploading results from a previous study for treatment patterns but I get a similar thing to what @albertpratsu reported in #112 - nothing happens after saying upload complete. Maybe it's a versioning problem again? If so it would be good to get an informative error

![image](https://github.com/darwin-eu-dev/ReportGenerator/assets/9583964/e5f85b35-049a-40dd-82ef-780af647ded3)

**Comment by cbarbozaerasmus** [comment]
Hey. Yes, probably is the versioning problem. I did a quick fix, and it should accept results now from version 2.5.0 and version 2.5.2. 

I think the only difference is the column index_year/indexYear. 

I'll include a warning message that informs the type of error. 

Thanks a lot.

**Comment by cbarbozaerasmus** [comment]
Message included to inform the user data didn't pass the check.
