### ISSUE TITLE
Figures - Incidence/Prevalence - Unable to arrange/stack graphs

### ISSUE THREAD

**Issue by j-politi** [darwin-eu-dev/ReportGenerator#126]
We wanted to stack a few graphs by drug type. Maybe the figures could come out unfixed? 
Please see below for an example of the RepGen figure and the one we were trying to replicate.  
<img width="581" alt="Screen Shot 2024-02-09 at 9 11 33 AM" src="https://github.com/darwin-eu-dev/ReportGenerator/assets/159040979/93bed9b3-2087-4005-aaab-13d40b2ad8e3">
<img width="733" alt="Screen Shot 2024-02-09 at 9 11 08 AM" src="https://github.com/darwin-eu-dev/ReportGenerator/assets/159040979/db1024dd-462d-47ad-b89e-4d6395995fde">

**Comment by antonbarchuk** [comment]
Also, there's an option to change the figures' resolution and size in the Shiny app, which is quite useful for generating figures for the reports.

**Comment by ginberg** [comment]
@j-politi I am wondering how you created the 2nd figure? I am looking in the shiny app of the Opiods study but I don't see an option to arrange graphs in a certain way. [shinyapp
](https://data-dev.darwin-eu.org/content/e3479785-bf65-41e5-9777-84b4d1c5bd9f/)

**Comment by j-politi** [comment]
@ginberg This was the original figure in the study report that we were trying to replicate. This was not generated by us.

**Comment by ginberg** [comment]
<img width="1075" alt="Screenshot 2024-03-05 at 13 35 44" src="https://github.com/darwin-eu-dev/ReportGenerator/assets/7089667/fb57d47d-e808-4539-b2de-9dcfc4ead137">

stacking of faceted plots is now possible. Also the width of the plot in the report has been adjusted

**Comment by j-politi** [comment]
[like]  Julieta Politi (DARWIN EU® CC) reacted to your message:
________________________________
