### ISSUE TITLE
DataPartner labelling function

### ISSUE THREAD

**Issue by j-politi** [darwin-eu-dev/ReportGenerator#130]
It would be nice to be able to label each DP individually, from the RepGen.

**Comment by ginberg** [comment]
@j-politi we are not totally sure what you mean with this. Could you explain a bit more? Do you have in mind on how this labeling functionality would look like in the RepGen?

**Comment by j-politi** [comment]
@ginberg I think that now, the default label is the file's name. It would be nice to be able to add a label to each file - maybe from the dashboard?

**Comment by ginberg** [comment]
@j-politi the name of the data partner is coming from the "cdm_name" inside the csv file. So typically it looks something like this. You would look to be able to change these names or something else?
<img width="310" alt="Screenshot 2024-02-27 at 15 16 50" src="https://github.com/darwin-eu-dev/ReportGenerator/assets/7089667/75228782-f548-410a-ae93-419d36c98ab1">

**Comment by j-politi** [comment]
Ohh, OK. For some reason, I thought it was dependent on the .csv file name.

**Comment by ginberg** [comment]
@j-politi no problem! But just to be sure, you would like to be able to change these data partner names?

**Comment by j-politi** [comment]
@ginberg If they are always standard, I guess it's unnecessary. So maybe we can close this issue...

**Comment by ginberg** [comment]
yes the data partners know what they have to fill in, so I also think we can close it.
