### ISSUE TITLE
Deselect option 

### ISSUE THREAD

**Issue by j-politi** [darwin-eu-dev/ReportGenerator#131]
Some drug lists/conditions are lengthy, and when many are selected, it would be nice to be able to deselect previous selections in just one click.

**Comment by ginberg** [comment]
@j-politi in case you can select multiple items, we have now added the "Select all" and "Deselect all" options. See this one for example
![Image](https://github.com/darwin-eu-dev/ReportGenerator/assets/7089667/5812429a-81dd-4163-9866-9164384ad9e8)
