### ISSUE TITLE
Can you plot multiple outcomes on one plot interactively?

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu-dev/ReportGenerator#14]
For this package are you able to plot multiple outcomes on one plot? Example of Ed's app which allows a user to add and take away outcomes on one plot or create separate facets. 
Example all on one plot
![image](https://user-images.githubusercontent.com/16097637/217842580-beb0aacd-2575-44b4-8aeb-5b3875eb3975.png)

Example outcome on facets
![image](https://user-images.githubusercontent.com/16097637/217843650-2ae18f29-32bc-4666-9a44-aae9b86f19ed.png)

**Comment by cbarbozaerasmus** [comment]
Added functionality in latest releases.
