### ISSUE TITLE
Fix button Shiny App Generator

### ISSUE THREAD

**Issue by cebarboza** [darwin-eu-dev/ReportGenerator#174]
Fix button to generate the Shiny App.

**Comment by ginberg** [comment]
we can close this one I guess @cebarboza ?
<img width="1048" alt="Screenshot 2024-05-21 at 14 40 39" src="https://github.com/darwin-eu-dev/ReportGenerator/assets/7089667/7f0e61c9-4cc4-4aa7-a79c-5ba86d0d3036">

**Comment by cebarboza** [comment]
Yes.
