### ISSUE TITLE
Developers: Menu to select study types on reportGenerator Shiny app

### ISSUE THREAD

**Issue by cbarbozaerasmus** [darwin-eu-dev/ReportGenerator#19]
After a zip file is uploaded with data from each study  #7, we need a menu to select study types, and then selects the tables and figures that will be in a report, that according to the Complete Catalogue of Standard Data Analyses (1.3.8.2). 

Currently the app looks like:

![image](https://user-images.githubusercontent.com/113351542/227555181-4eea3e65-21e4-4c16-aada-a6f8f7e15ba1.png)

Include options like:

![image](https://user-images.githubusercontent.com/113351542/227555362-de512869-03e9-4a2b-9b6f-d3b3fe983464.png)

**Comment by ginberg** [comment]
hi @cbarbozaerasmus, I am wondering how to filter the report items based on the study type? Should we extend the itemsConfig.csv ?

**Comment by cbarbozaerasmus** [comment]
No longer a feature required by the package.
