### ISSUE TITLE
Users: What functions for IncidencePrevalence are still missing from the Style Guide?

### ISSUE THREAD

**Issue by cbarbozaerasmus** [darwin-eu-dev/ReportGenerator#34]
Open an issue to request the development of a specific figure and table missing from the ReportGenerator Style Guide. 

Please state:

What Table/Figure is missing in ReportGenerator, from the Style Guide?

Relation to the Catalog of Standard Analysis (What type of study, data, etc). 

Suggest a name, details, input, output, and other details to generate and document the table and figure.

**Comment by NicolaBarclay** [comment]
Figure adding in a vertical line to indicate some sort of 'interruption' (i.e. change in policy/an event such as lockdown, etc.). Example on page 33 of style guide. Perhaps this could be an option to include on every plot, or a single plot, as specified by the user
