### ISSUE TITLE
generateMockData() throwing an error

### ISSUE THREAD

**Issue by NicolaBarclay** [darwin-eu-dev/ReportGenerator#43]
Trying to run generateMockData() which throws this error

```
generateMockData()
[1] "SYNTHEA"
Error: 'computeQuery' is not an exported object from 'namespace:CDMConnector'
In addition: Warning message:
 Error: 'computeQuery' is not an exported object from 'namespace:CDMConnector'
```
Is this due to a dependency with CDMConnector? I'm running version 0.3.1

**Comment by ginberg** [comment]
hi @NicolaBarclay yes this function has been added recently to CDMConnector. I am using version 0.5.0 and I don't have any problem running generateMockData()

**Comment by NicolaBarclay** [comment]
Great, just updated CDMConnector and this now works :-)
