### ISSUE TITLE
Problem uploading files into reportGenerator app

### ISSUE THREAD

**Issue by NicolaBarclay** [darwin-eu-dev/ReportGenerator#44]
1. When uploading a single .csv file into the reportGenerator shiny I get the following error:

`Error: object 'csvFiles' not found`

![image](https://user-images.githubusercontent.com/55543107/228188654-70b54fb1-fbbf-4d22-9b58-7d8e4ad0441d.png)

2. When uploading a zip file, i get the message 'uploading compete' but then no options in the 'item selection' section of the app.

![image](https://user-images.githubusercontent.com/55543107/228188317-c4cb895f-598a-4a2a-9fbb-64ace9453ac2.png)

**Comment by NicolaBarclay** [comment]
Hi @ginberg, I have just done a package install, and yes, I can now see the files when i upload a zip. But if I try to upload a single csv i still get the same error.

**Comment by ginberg** [comment]
hi @NicolaBarclay, ok good to know the zip works. The single csv error should be solved after @cbarbozaerasmus has merged https://github.com/darwin-eu-dev/ReportGenerator/pull/46
