### ISSUE TITLE
Warning messages after installing ReportGenerator

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu-dev/ReportGenerator#47]
After running the following lines of code:
```
install.packages("remotes")
remotes::install_github("darwin-eu-dev/reportGenerator", force = TRUE)

library(ReportGenerator)
There were 16 warnings (use warnings() to see them)
warnings()
```

and installing package i get the following warning messages below:

Warning messages:
1: replacing previous import ‘flextable::set_caption’ by ‘huxtable::set_caption’ when loading ‘ReportGenerator’
2: replacing previous import ‘flextable::italic’ by ‘huxtable::italic’ when loading ‘ReportGenerator’
3: replacing previous import ‘flextable::height’ by ‘huxtable::height’ when loading ‘ReportGenerator’
4: replacing previous import ‘flextable::valign’ by ‘huxtable::valign’ when loading ‘ReportGenerator’
5: replacing previous import ‘flextable::font’ by ‘huxtable::font’ when loading ‘ReportGenerator’
6: replacing previous import ‘ggplot2::theme_grey’ by ‘huxtable::theme_grey’ when loading ‘ReportGenerator’
7: replacing previous import ‘flextable::bold’ by ‘huxtable::bold’ when loading ‘ReportGenerator’
8: replacing previous import ‘dplyr::add_rownames’ by ‘huxtable::add_rownames’ when loading ‘ReportGenerator’
9: replacing previous import ‘flextable::as_flextable’ by ‘huxtable::as_flextable’ when loading ‘ReportGenerator’
10: replacing previous import ‘flextable::align’ by ‘huxtable::align’ when loading ‘ReportGenerator’
11: replacing previous import ‘flextable::width’ by ‘huxtable::width’ when loading ‘ReportGenerator’
12: replacing previous import ‘huxtable::to_rtf’ by ‘officer::to_rtf’ when loading ‘ReportGenerator’
13: replacing previous import ‘huxtable::to_html’ by ‘officer::to_html’ when loading ‘ReportGenerator’
14: replacing previous import ‘DT::dataTableOutput’ by ‘shiny::dataTableOutput’ when loading ‘ReportGenerator’
15: replacing previous import ‘DT::renderDataTable’ by ‘shiny::renderDataTable’ when loading ‘ReportGenerator’
16: replacing previous import ‘huxtable::markdown’ by ‘shiny::markdown’ when loading ‘ReportGenerator’

**Expected result:** installed package with no warning messages

**Comment by ginberg** [comment]
@daniellenewby this should be solved after the open PR is merged
https://github.com/darwin-eu-dev/ReportGenerator/pull/46

**Comment by daniellenewby** [comment]
Yes! Thank you  now there are no warning messages
