### ISSUE TITLE
Unable to open report generator after implementing generateMockData()

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu-dev/ReportGenerator#48]
```
library(ReportGenerator)
There were 16 warnings (use warnings() to see them)
generateMockData()
```
Below is screenshot and in the console is the following information and now report generator no longer runs unless i completely close R studio

Loading required package: shiny

Listening on http://127.0.0.1:4928
Warning in file() :
  cannot open file 'C:\Users\dnewby\AppData\Local\Temp\Rtmp4kYLpN\Rf555452ed1af5': No such file or directory
Warning: Error in file: cannot open the connection
  87: file
  86: createRenderPrintPromiseDomain
  85: renderFunc
  84: output$uploadedFiles
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Warning in file(open = "w+b", encoding = "UTF-8") :
  cannot open file 'C:\Users\dnewby\AppData\Local\Temp\Rtmp4kYLpN\Rf555457cc1466': No such file or directory
Error in file(open = "w+b", encoding = "UTF-8") : 
  cannot open the connection

![image](https://user-images.githubusercontent.com/16097637/228358836-f1469015-17f2-4414-94ec-0c8c834de0b5.png)

**Comment by Xintong-Li-ZnCu** [comment]
I got the same error message, but after I restarted R and reran `reportGenerator()` it worked

**Comment by cbarbozaerasmus** [comment]
The error is related on how R is creating the temporary directories. I'll hope to fix this today. The workaround is far from ideal, but as Xintong said, restarting make reportGenerator() functional again.
